# Cloudflare Worker config
name               = "rickroll-scheduler"
main               = "index.js"
compatibility_date = "2024-01-01"

[vars]
ONESIGNAL_APP_ID = "f9a948e0-79d4-46d7-9fae-6edb3f2b361d"

# Sau khi deploy chạy lệnh này để set secret:
# wrangler secret put ONESIGNAL_REST_API_KEY
# paste: os_v2_app_7guurydz2rdnph5on3nt6kzwdwyaqshodfduwl5w2bdpowc7gkteyklzjq2gnc2wetdu4gcsm2b6zsjjowsdhjiyms37u42qu2srzaa
